version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend service
  backend:
    build:
      context: ./apps/backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
    - ./apps/backend/secrets/google-api.json:/usr/src/app/secrets/google-api.json:ro
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/secrets/google-api.json


  # Frontend service
  frontend:
    build:
      context: ./apps/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/usr/src/app

volumes:
  mongodb_data: